### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by stephane-flesch** [charlesveasey/vDome#2]
Hello,
I am trying to map video on a dome for a school project.

I tried to compile and build vDome is xCode (v5.1.1)
Not sure that I do it right, as I am new to xCode.

I get 3 errors:

clang: error: no such file or directory: '/Users/stephaneflesch/Documents/openFrameworks/addons/ofxHapPlayer/src/HapMovieRenderer.m'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

clang: error: no such file or directory: '/Users/stephaneflesch/Documents/openFrameworks/addons/ofxHapPlayer/src/HapOFPixelBufferTexture.m'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

clang: error: no such file or directory: '/Users/stephaneflesch/Documents/openFrameworks/addons/ofxHapPlayer/src/ofxHapPlayer.mm'
clang: warning: -lpthread: 'linker' input unused
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

Am I doing something wrong?
Thanks in advance for your help.

Best regards,

Stéphane

**Comment by sakalcik** [comment]
Hello, i am interested in your software. I have portable dome and want use 2 projectors for fulldome videos projection. I download all programs which is in Github, but i don't know how it install. I don't know how do compiling. When i download i must do compiling with visual or code blocks? Maybe you can write how do all step by step? Its very important for me. It's one of the best work which i  see. Thanks immediately.

**Comment by charlesveasey** [comment]
Hello,

I am away from the office but can try to help.
What operating system are you using?

**Comment by sakalcik** [comment]
I use win 7, 64 bit
2015 kov. 31 07:10 "Charles Veasey" <notifications@github.com> rašė:

> Hello,
>
> I am away from the office but can try to help.
> What operating system are you using?
>

**Comment by sakalcik** [comment]
If you help I will be very grateful. It's very important for me

2015-03-31 8:52 GMT+03:00 Karolis Sakalcik <karolis.sakalcik@gmail.com>:

> I use win 7, 64 bit
> 2015 kov. 31 07:10 "Charles Veasey" <notifications@github.com> rašė:
>
>> Hello,
>>
>> I am away from the office but can try to help.
>> What operating system are you using?
>>
>> On Sunday, March 29, 2015, sakalcik <notifications@github.com> wrote:
>>
>> > Hello, i am interested in your software. I have portable dome and want
>> use
>> > 2 projectors for fulldome videos projection. I download all programs
>> which
>> > is in Github, but i don't know how it install. I don't know how do
>> > compiling. When i download i must do compiling with visual or code
>> blocks?
>> > Maybe you can write how do all step by step? Its very important for me.
>> > It's one of the best work which i see. Thanks immediately.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/charlesveasey/vDome/issues/2#issuecomment-87557025
>> >.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/charlesveasey/vDome/issues/2#issuecomment-87928046>.
>>
>


-- 
Nuoširdžiai | Best Regards,
*Karolis Sakalčik*
Tel: +37065736696
Mail: *karolis.sakalcik@gmail.com <karolis.sakalcik@gmail.com>*

**Comment by sakalcik** [comment]
Hello Charle are you can help me to compile and enjoy this program?

2015-03-31 11:05 GMT+03:00 Karolis Sakalcik <karolis.sakalcik@gmail.com>:

> If you help I will be very grateful. It's very important for me
>
> 2015-03-31 8:52 GMT+03:00 Karolis Sakalcik <karolis.sakalcik@gmail.com>:
>
>> I use win 7, 64 bit
>> 2015 kov. 31 07:10 "Charles Veasey" <notifications@github.com> rašė:
>>
>>> Hello,
>>>
>>> I am away from the office but can try to help.
>>> What operating system are you using?
>>>
>>> On Sunday, March 29, 2015, sakalcik <notifications@github.com> wrote:
>>>
>>> > Hello, i am interested in your software. I have portable dome and want
>>> use
>>> > 2 projectors for fulldome videos projection. I download all programs
>>> which
>>> > is in Github, but i don't know how it install. I don't know how do
>>> > compiling. When i download i must do compiling with visual or code
>>> blocks?
>>> > Maybe you can write how do all step by step? Its very important for me.
>>> > It's one of the best work which i see. Thanks immediately.
>>> >
>>> > —
>>> > Reply to this email directly or view it on GitHub
>>> > <https://github.com/charlesveasey/vDome/issues/2#issuecomment-87557025
>>> >.
>>> >
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/charlesveasey/vDome/issues/2#issuecomment-87928046>.
>>>
>>
>
>
> --
> Nuoširdžiai | Best Regards,
> *Karolis Sakalčik*
> Tel: +37065736696
> Mail: *karolis.sakalcik@gmail.com <karolis.sakalcik@gmail.com>*
>



-- 
Nuoširdžiai | Best Regards,
*Karolis Sakalčik*
Tel: +37065736696
Mail: *karolis.sakalcik@gmail.com <karolis.sakalcik@gmail.com>*

**Comment by charlesveasey** [comment]
The compilation instructions are the same for openFrameworks with additional requirements for vDome outlined in the readme. In your case you will need to download Visual Studio Express 2012. In order to compile the vDome Player you will need to download Qt-5 for Visual Studio 2012.  

Here is the latest build for Windows in case if you still have trouble compiling:
https://www.dropbox.com/s/ubm4cxir034lzkb/vDome-2014-11-21-win.zip?dl=0

Even with the built version there are some additional libraries needed and the easiest way to obtain them is to download Visual Studio Express 2012 and Qt-5.

-Charles

**Comment by sakalcik** [comment]
Hello Charle I install Qt-5 enterprise and visual studio express 2012. And
visual studio qt addin 1.2.4. When i install all this. I must do all with
visual? And which file from yours drop box link i must compile? Vdome
application?  Or i need compile file from internet vdome master or
vdome-player- master?

2015-04-02 15:55 GMT+03:00 Charles Veasey <notifications@github.com>:

> The compilation instructions are the same for openFrameworks with
> additional requirements for vDome outlined in the readme. In your case you
> will need to download Visual Studio Express 2012. In order to compile the
> vDome Player you will need to download Qt-5 for Visual Studio 2012.
>
> Here is the latest build for Windows in case if you still have trouble
> compiling:
> https://www.dropbox.com/s/ubm4cxir034lzkb/vDome-2014-11-21-win.zip?dl=0
>
> Even with the built version there are some additional libraries needed and
> the easiest way to obtain them is to download Visual Studio Express 2012
> and Qt-5.
>
> -Charles
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/charlesveasey/vDome/issues/2#issuecomment-88887662>.
>



-- 
Nuoširdžiai | Best Regards,
*Karolis Sakalčik*
Tel: +37065736696
Mail: *karolis.sakalcik@gmail.com <karolis.sakalcik@gmail.com>*

**Comment by charlesveasey** [comment]
The Dropbox link doesn't need compilation, just double click on the
vDome.exe file.

If you don't see anything, check the setting file, delete the
settings folder and cross reference the manual to configure for your dome.

**Comment by sakalcik** [comment]
Hello, thanks for application. I have questions for you about settings. I
attach my computer parameters are it's good for my system? I will use 2 or
3 Full Hd 1920x1080 projectors and control monitor. Control monitor must be
main.
Which resolution i must use whe i use 2 projectors and my films is full hd
format 1920x1080. In example is 2048. I need 1920?
1) In example was window width 6144 or in my case window width is
2*1920=3840. Yes?
2) So my settings is <window position="1920,0"when zero 0 is not zero? What
does it do?
3)resolution="3840,1080> 1080 because projector is 1920x1080. I think
correct?
3)If i have 6 meters dome. which radius must be. If i will set projector
near the dome wall so my radius will be 3 meters? Or it must be 360 deg?
4)If i use 2 projectors. My FOV will be 360/2=180?
5) Position parameters when grid is 3 meters so position="0,0,3"? When zero
is not zero?
6) input file="" must be place where i have all videos for exmple if my
domemaster file is in C:\Users\Deivis\Desktop\BCT.mp4 So must be input
file="C:\Users\Deivis\Desktop\BCT.mp4"? And if i have in this folder five
movies i can set input file="C:\Users\Deivis\Desktop" Or i allways must
change settings when i show new film?
7)When need write source media? and when grid or capture? When i show films
i write media or when i do calibration i write grid?
8) Scale 1 means that its full resolution?
9) Levels values must be from 0-1, but in examples is 0, 255?

Maybe you can answer to question numbered.
Thanks Charle





2015-04-03 16:38 GMT+03:00 Charles Veasey <notifications@github.com>:

> The Dropbox link doesn't need compilation, just double click on the
> vDome.exe file.
>
> If you don't see anything, check the setting file, delete the
> settings folder and cross reference the manual to configure for your dome.
>
> On Thursday, April 2, 2015, sakalcik <notifications@github.com> wrote:
>
> > Hello Charle I install Qt-5 enterprise and visual studio express 2012.
> And
> > visual studio qt addin 1.2.4. When i install all this. I must do all with
> > visual? And which file from yours drop box link i must compile? Vdome
> > application? Or i need compile file from internet vdome master or
> > vdome-player- master?
> >
> > 2015-04-02 15:55 GMT+03:00 Charles Veasey <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
> >
> > > The compilation instructions are the same for openFrameworks with
> > > additional requirements for vDome outlined in the readme. In your case
> > you
> > > will need to download Visual Studio Express 2012. In order to compile
> the
> > > vDome Player you will need to download Qt-5 for Visual Studio 2012.
> > >
> > > Here is the latest build for Windows in case if you still have trouble
> > > compiling:
> > >
> https://www.dropbox.com/s/ubm4cxir034lzkb/vDome-2014-11-21-win.zip?dl=0
> > >
> > > Even with the built version there are some additional libraries needed
> > and
> > > the easiest way to obtain them is to download Visual Studio Express
> 2012
> > > and Qt-5.
> > >
> > > -Charles
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/charlesveasey/vDome/issues/2#issuecomment-88887662
> >.
> > >
> >
> >
> >
> > --
> > Nuoširdžiai | Best Regards,
> > *Karolis Sakalčik*
> > Tel: +37065736696
> > Mail: *karolis.sakalcik@gmail.com
> > <javascript:_e(%7B%7D,'cvml','karolis.sakalcik@gmail.com');> <
> > karolis.sakalcik@gmail.com
> > <javascript:_e(%7B%7D,'cvml','karolis.sakalcik@gmail.com');>>*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/charlesveasey/vDome/issues/2#issuecomment-89162575>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/charlesveasey/vDome/issues/2#issuecomment-89290202>.
>



-- 
Nuoširdžiai | Best Regards,
*Karolis Sakalčik*
Tel: +37065736696
Mail: *karolis.sakalcik@gmail.com <karolis.sakalcik@gmail.com>*

**Comment by charlesveasey** [comment]
Yes, you should use three projectors, like the image I've attached below.
Set the projectors positions in the settings.xml file to the relative
positions. If you want to play HD video on the dome, I'd still set the
input resolution to 2048 or 1080, depending on whether want to letterbox or
crop the video. The dome is inherently a circular (or square video) aspect
ratio.

Window width would be 1920 * 3 = 5760.
Window height = 1080.

Projector resolution = 1920 x 1080.

Window position is related to what is says in the Windows control panel -
monitor settings.

Radius is in units - arbitrary really, not a real size. Can leave to the
default usually.

Easiest just to set FOV by eye, especially if you have only three
projectors.

Write (saving) only saves settings - does not render video file.

Easiest way to set the media folder is to drag / drop video file onto the
vDome window. Can also drag / drop m3u playlist file. It is best to use
vDome's player interface (VLC-like media interface)
https://github.com/charlesveasey/vDome-player

To compile the player - install Qt and then double click the .pro file from
the above repository. Then click the play icon in the Qt builder interface.

You can change the video format from domemaster to HD in the vDome menu -
Input -> Format (can only change to HD on media, capture, or spout input)

It is best to play around with the settings when projecting on the dome to
understand the effect.

Generally I do a very rough alignment with the settings under the Setup
category, then use the Warp category for the alignment.

Levels values may be mis-documented either 0-1 or 0-255 means the same
thing.

If there you see something different from the settings.xml file versus the
documentation, go with the settings.xml file (sorry!).

For blending and masking you should use high-quality gaffers tape or
similar to create a triangle shaped physical mask, because the overlap will
not enable you to see black but rather grey unless you physically mask
them. Then use the software masking to touch up the physical mask. It might
help to physically mask the projectors before working too much with the
spatial calibration.

Also, since I have generally work with six projectors at 1024 x 768, there
might be some mistake in the code at 1920 x 1080, if you see something like
half an image or similar, there might be some resolution hardcoded or not
being updated properly from the xml. I hope not the case, but if so let me
know please!

[image: Inline image 1]

**Comment by charlesveasey** [comment]
![3-projectors](https://cloud.githubusercontent.com/assets/3144590/7000649/ac4724a8-dbe6-11e4-80db-3b74c29c2863.jpg)

**Comment by sakalcik** [comment]
Hello, or i can use 2 projectors? Or minimal projectors number is 3?

2015-04-06 7:54 GMT+03:00 Charles Veasey <notifications@github.com>:

> [image: 3-projectors]
> <https://cloud.githubusercontent.com/assets/3144590/7000649/ac4724a8-dbe6-11e4-80db-3b74c29c2863.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/charlesveasey/vDome/issues/2#issuecomment-89918057>.
>



-- 
Nuoširdžiai | Best Regards,
*Karolis Sakalčik*
Tel: +37065736696
Mail: *karolis.sakalcik@gmail.com <karolis.sakalcik@gmail.com>*

**Comment by charlesveasey** [comment]
I think using two would require special lenses, three is somewhat common
for example the LA company Vortex uses three.

Of course you can try two and see what happens.

**Comment by crapulent** [comment]
Hello, thank you for this software.
I did not yet tested it on the real dome, but I have question regarding this point
> For blending and masking you should use high-quality gaffers tape or
similar to create a triangle shaped physical mask, because the overlap will
not enable you to see black but rather grey unless you physically mask
them. Then use the software masking to touch up the physical mask. It might
help to physically mask the projectors before working too much with the
spatial calibration.

Is there any reason to use hardware masking approach, or I can for example replace ending of data/settings/shaders/vdome.frag with
>     float mask = texture(maskTex, vtexcoord).a;
>
>     cRGB.r *= 1-mask;
>     cRGB.g *= 1-mask;
>     cRGB.b *= 1-mask;
> 
>     outputColor = vec4(cRGB.rgb, 1);

in 'production' setup without any problems? Thanks

**Comment by charlesveasey** [comment]
The reason for hardware masks is that most projectors do not emit a pure
black. It is usually somewhat grey - not really the absence of light. The
problem occurs when you overlap projectors you will have the option of
either showing the overlap during black parts of the film (or whatever you
are projecting) or to raise the lowest black level to match overlap area,
thus severely compressing the color space. Many people will just live with
being able to see the overlap during black parts. Personally I prefer to
use physical masks in order to block the unused light, but you should do
what works best for your content and dome.


On Tue, Apr 14, 2015 at 10:54 AM, Alexander Vtorov <notifications@github.com
